### ISSUE TITLE
Block Reader suggestion

### ISSUE THREAD

**Issue by jajajafeti** [IntelligenceModding/Advanced-Peripherals-Documentation#16]
Hey, I just tested out the blockreader and wanted to get the growth level of my wheat, but realised it can only give the data of a tile entity. I would like to have the same feature for the block reader, which all Turtels already have.
The Turtel has the function `inspect()` and returns a table with the block states.
http://www.computercraft.info/wiki/Turtle.inspect as you can see here the description.

Thanks.

**Comment by SirEndii** [comment]
Wrong repository -> https://github.com/Seniorendi/AdvancedPeripherals
