### ISSUE TITLE
Bug with Colony Integrator

### ISSUE THREAD

**Issue by bindwkill** [IntelligenceModding/Advanced-Peripherals-Documentation#17]
I don't know if I made something wrong, but when call the "getRequests()" function, the follow message is displayed:

"Java Exception Thrown: java.lang.ClassCastException: com.minecolonies.api.colony.requestsystem.requestable.deliveryman.Pickup cannot be cast to com.minecolonies.api.colony.requestsystem.requestable.IDeliverable. "

Apparently happens if there is a "pickup" request in the colony.

**Comment by SirEndii** [comment]
Wrong repository 
Please report bugs here -> https://github.com/Seniorendi/AdvancedPeripherals/issues
