### ISSUE TITLE
Redstone Integrator texture is the same on all sides.

### ISSUE THREAD

**Issue by SkyTheCodeMaster** [IntelligenceModding/Advanced-Peripherals-Documentation#19]
As in the title, there is no obvious "front" side of the redstone integrator.
I see two ways to remedy this:
1) The "preferable" way: Remove `left`, `front`, etc, directions and switch to cardinal directions, `north`, `east`, `south`, `west`, `up`, and `down`.
2) The easier way: Add obvious sides to the texture.

Obviously, I'd prefer the first method because it it will bring this to 1:1 parity with Plethora's redstone integrator.

**Comment by SirEndii** [comment]
The redstone integrator already supports cardinal directions and the directions `left`, `front`, ...
And this is the wrong repository.
