### ISSUE TITLE
getRequests() on colony Integrator error

### ISSUE THREAD

**Issue by AudBobb** [IntelligenceModding/Advanced-Peripherals-Documentation#21]
attempting to call getRequests() on a wrapped colony integrator returns Java Exception thrown:
java.lang.NullPointerException

associated code 

https://pastebin.com/6zq5JW5Q

**Comment by AudBobb** [comment]
Have attempted restarting server, method worked fine for days, then woke up this morning to it throwing that error with no changes. worked intermittently throughout the morning before completely failing to work.

**Comment by SirEndii** [comment]
You're at the wrong repository, and you're not giving me information about the mod and minecraft instance. And we always need a log.
Create a repository at https://github.com/Seniorendi/AdvancedPeripherals .
