### ISSUE TITLE
[1.16] Redstone Integrator Set* does nothing.

### ISSUE THREAD

**Issue by ArchAngel075** [IntelligenceModding/Advanced-Peripherals-Documentation#27]
Using modpack Enigmatica 6, MC 1.16

Redstone integrator setAnalogOutput/setOutput does nothing.

get* works with external redstone input calls.

Edit:

Seems the set* commands read the state from computer not from the integrator. IE `setOutput("top",true)` sets the computers top rs high not the integrators top. Is this intended.

**Comment by SirEndii** [comment]
Wrong repository
Please report bugs to https://github.com/Seniorendi/AdvancedPeripherals
