### ISSUE TITLE
Geoscanning turtle pages have outdated links

### ISSUE THREAD

**Issue by daniilfurgen** [IntelligenceModding/Advanced-Peripherals-Documentation#33]
### Descripe

On those pages, links to Geo Scanner are outdated and link to page pre version separation 

### Steps to reproduce

1. Go to Geoscanning Turtle page like this -> https://docs.srendi.de/1.16/turtles/geo_scanner_turtle/
2. Click on link to Geo Scanner page
3. Internet magic
4. Get 404 error

### Direct URL

https://docs.srendi.de/1.16/turtles/geo_scanner_turtle/

**Comment by SirEndii** [comment]
Fixed
