### ISSUE TITLE
How to connec the ME Bridge?

### ISSUE THREAD

**Issue by StathisKap** [IntelligenceModding/Advanced-Peripherals-Documentation#36]
### Descripe

I want to access my ae2 system through the ME Bridge, but the ae2 cables won't connect to the bridge? what am I missing? I think this should be added to the documentation (happy to do it)

### Steps to reproduce

place an ME Bridge next to any cable from ae2

### Direct URL

https://docs.srendi.de/1.18/peripherals/me_bridge/

**Comment by SirEndii** [comment]
Hey
Could you tell me the version you use?
If you want to improve the docs, you can do it. Some documentation help is always welcome

But if you need help with the mod, use the discussions feature on github or join us on discord

**Comment by StathisKap** [comment]
Hey, I don't remember which version it was. But after restarting my game (without updating) and breaking the block and placing it down a couple of times. It worked. Then I updated and it was working fine.

And yeah I might make some PR for the docs after I get some more free time. I'd love to help

**Comment by SirEndii** [comment]
> Hey, I don't remember which version it was. But after restarting my game (without updating) and breaking the block and placing it down a couple of times. It worked. Then I updated and it was working fine.

Sweet to hear 
If you have more issues with the mod, you can report them [here](https://github.com/Seniorendi/AdvancedPeripherals/issues)
Or ask for help on our [discord](https://discord.com/invite/QuF3hWDtWC)
