### ISSUE TITLE
AE2 bridge screenshots broken

### ISSUE THREAD

**Issue by Quezler** [IntelligenceModding/Advanced-Peripherals-Documentation#47]
### Descripe

The 3 picture examples at each of these pages fail to load:

https://docs.intelligence-modding.de/1.16/peripherals/me_bridge/
https://docs.intelligence-modding.de/1.18/peripherals/me_bridge/
https://docs.intelligence-modding.de/1.19/peripherals/me_bridge/

One of them (though probably all of them) return an apache 404 error:
https://intelligence-modding.de/wp-content/uploads/2021/02/Bild_2021-02-05_231136.png

### Steps to reproduce

1. Try to look at the example data from `listItems()`, 'getCraftingCPUs', or `craftItem()`
2. Notice only the `alt` of the `img` rendering

### Direct URL

see above ^

**Comment by SirEndii** [comment]
yeah... I accidentally deleted them all
Maybe I can find a backup
