### ISSUE TITLE
Clarify that ME (and presumably RS) bridges can accept a tag as the item.name value in various methods

### ISSUE THREAD

**Issue by trunksbomb** [IntelligenceModding/Advanced-Peripherals-Documentation#64]
### Describe

Documentation should indicate two things:
1. The `item` parameter in functions is used to construct a filter. This is implied but it would be better if made explicitly clear.
2. You can filter based on tag by specifying the name as `#thetag` as in the following example: `meBridge.exportItemToPeripheral({name="#forge:ores"}, peripheralName)`

### Steps to reproduce

NA

### Direct URL

https://docs.intelligence-modding.de/peripherals/me_bridge/#getitem

**Comment by SirEndii** [comment]
I agree with you there, but I would add a reference to the [filters guide ](https://docs.intelligence-modding.de/guides/filters/#filters) with a small explanation

**Comment by trunksbomb** [comment]
I think you got your link wrong :)

**Comment by trunksbomb** [comment]
Related issue: I had no idea there was a Filters guide!

**Comment by SirEndii** [comment]
Woops, fixed

**Comment by SirEndii** [comment]
> Related issue: I had no idea there was a Filters guide!

Yeah, I need to clarify that better in the docs
